### ISSUE TITLE
OKBoard actually doesn't support screen sizes bigger than 6' in SailfishOS

### ISSUE THREAD

**Issue by ferlanero** [teleshoes/okb-keyboard#1]
OKBoard actually doesn't support 6,5' screen sizes in SailfishOS which means that it can't be used on some Jolla official devices like the new Sony Xperia 10 Plus.

The app shows the message "Screen size not supported" and it doesn't allow to swipe over the keyboard.

Do you think that could be there any solution to this problem, please?

**Comment by teleshoes** [comment]
i am not the developer, i just forked it on github for my own convenience. good luck!
please see: https://git.tuxfamily.org/okboard/okb-keyboard.git/
